### ISSUE TITLE
miscellaneous test failures

### ISSUE THREAD

**Issue by petrelharp** [tskit-dev/msprime#1062]
With dcaae175c42727d7f00c0f54cc997292df2b228c, updated submodules, and freshly-compiled, I get the following errors:
```
======================================================================
ERROR: test_correct_streams (tests.test_cli.TestMspmsOutput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/peter/projects/tskit-dev/msprime/tests/test_cli.py", line 1147, in test_correct_streams
    stdout, stderr = capture_output(cli.mspms_main, args.split())
  File "/home/peter/projects/tskit-dev/msprime/tests/test_cli.py", line 56, in capture_output
    func(*args, **kwargs)
  File "/home/peter/projects/tskit-dev/msprime/msprime/cli.py", line 1009, in mspms_main
    sr.run(sys.stdout)
  File "/home/peter/projects/tskit-dev/msprime/msprime/cli.py", line 305, in run
    self.print_trees(tree_sequence, output)
  File "/home/peter/projects/tskit-dev/msprime/msprime/cli.py", line 275, in print_trees
    newick = tree.newick(precision=self._precision)
  File "/home/peter/.local/lib/python3.7/site-packages/tskit-0.2.4.dev0-py3.7-linux-x86_64.egg/tskit/trees.py", line 2088, in newick
    precision=precision, root=root, buffer_size=buffer_size
_tskit.LibraryError: Supplied buffer is too small
-------------------- >> begin captured logging << --------------------
msprime.ancestry: DEBUG: Setting initial model {'name': 'hudson'}
msprime.ancestry: DEBUG: Running simulation until maximum: inf
--------------------- >> end captured logging << ---------------------

======================================================================
ERROR: test_ooa_model (tests.test_doc_examples.TestDocumentationExamples)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/peter/projects/tskit-dev/msprime/tests/test_doc_examples.py", line 64, in test_ooa_model
    correct_model.verify_equal(local_model)
  File "/home/peter/.local/lib/python3.7/site-packages/stdpopsim-0.1.2.dev79+ng68948e7-py3.7.egg/stdpopsim/models.py", line 246, in verify_equal
    rtol=rtol, atol=atol)
  File "/home/peter/.local/lib/python3.7/site-packages/stdpopsim-0.1.2.dev79+ng68948e7-py3.7.egg/stdpopsim/models.py", line 96, in verify_demographic_events_equal
    raise UnequalModelsError("Different numbers of demographic events")
stdpopsim.models.UnequalModelsError: Different numbers of demographic events

======================================================================
FAIL: test_two_rows (tests.test_dict_encoding.TestBadLengths)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/peter/projects/tskit-dev/msprime/tests/test_dict_encoding.py", line 259, in test_two_rows
    self.verify(2)
  File "/home/peter/projects/tskit-dev/msprime/tests/test_dict_encoding.py", line 256, in verify
    lwt.fromdict(d)
AssertionError: ValueError not raised
-------------------- >> begin captured logging << --------------------
msprime.ancestry: DEBUG: Setting initial model {'name': 'hudson'}
msprime.ancestry: DEBUG: Running simulation until maximum: inf
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_zero_rows (tests.test_dict_encoding.TestBadLengths)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/peter/projects/tskit-dev/msprime/tests/test_dict_encoding.py", line 262, in test_zero_rows
    self.verify(0)
  File "/home/peter/projects/tskit-dev/msprime/tests/test_dict_encoding.py", line 256, in verify
    lwt.fromdict(d)
AssertionError: ValueError not raised
-------------------- >> begin captured logging << --------------------
msprime.ancestry: DEBUG: Setting initial model {'name': 'hudson'}
msprime.ancestry: DEBUG: Running simulation until maximum: inf
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_2d_array (tests.test_dict_encoding.TestBadTypes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/peter/projects/tskit-dev/msprime/tests/test_dict_encoding.py", line 220, in test_2d_array
    self.verify_columns([[1, 2], [3, 4]])
  File "/home/peter/projects/tskit-dev/msprime/tests/test_dict_encoding.py", line 217, in verify_columns
    lwt.fromdict(d)
AssertionError: ValueError not raised
-------------------- >> begin captured logging << --------------------
msprime.ancestry: DEBUG: Setting initial model {'name': 'hudson'}
msprime.ancestry: DEBUG: Running simulation until maximum: inf
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_str (tests.test_dict_encoding.TestBadTypes)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/peter/projects/tskit-dev/msprime/tests/test_dict_encoding.py", line 223, in test_str
    self.verify_columns("aserg")
  File "/home/peter/projects/tskit-dev/msprime/tests/test_dict_encoding.py", line 217, in verify_columns
    lwt.fromdict(d)
AssertionError: ValueError not raised
-------------------- >> begin captured logging << --------------------
msprime.ancestry: DEBUG: Setting initial model {'name': 'hudson'}
msprime.ancestry: DEBUG: Running simulation until maximum: inf
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_table_columns_match (tests.test_dict_encoding.TestEncodingMatchesTskit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/peter/projects/tskit-dev/msprime/tests/test_dict_encoding.py", line 107, in test_table_columns_match
    self.assertEqual(t1.keys(), t2.keys())
AssertionError: dict_keys(['left', 'right', 'parent', 'child', 'metadata', 'metadata_offset']) != dict_keys(['left', 'right', 'parent', 'child'])
-------------------- >> begin captured logging << --------------------
msprime.ancestry: DEBUG: Setting initial model {'name': 'hudson'}
msprime.ancestry: DEBUG: Running simulation until maximum: inf
--------------------- >> end captured logging << ---------------------

======================================================================
FAIL: test_missing_columns (tests.test_dict_encoding.TestMissingData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/peter/projects/tskit-dev/msprime/tests/test_dict_encoding.py", line 196, in test_missing_columns
    lwt.fromdict(d)
AssertionError: ValueError not raised
-------------------- >> begin captured logging << --------------------
msprime.ancestry: DEBUG: Setting initial model {'name': 'hudson'}
msprime.ancestry: DEBUG: Running simulation until maximum: inf
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------

```

Looks like there's some things to track down here... but, I'm confused - why didn't CI catch this?

**Comment by jeromekelleher** [comment]
Are you *sure* it's recompiled? This is exactly what it would look like if you had an old _msprime.so lying around the place.

**Comment by petrelharp** [comment]
Well, doing
```
make clean && make && python3 setup.py install --user && python3 -m nose -v tests/test_dict_encoding.py:TestMissingData
```
produces (after lots of compiling and things)
```
======================================================================
FAIL: test_missing_columns (tests.test_dict_encoding.TestMissingData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/peter/projects/tskit-dev/msprime/tests/test_dict_encoding.py", line 196, in test_missing_columns
    lwt.fromdict(d)
AssertionError: ValueError not raised
-------------------- >> begin captured logging << --------------------
msprime.ancestry: DEBUG: Setting initial model {'name': 'hudson'}
msprime.ancestry: DEBUG: Running simulation until maximum: inf
--------------------- >> end captured logging << ---------------------
```
.. and `make clean` is indeed removing `*.so`?

**Comment by petrelharp** [comment]
Same thing happens with a totally fresh clone of the git repo.

**Comment by benjeffery** [comment]
I can't recreate this.
Can you do:
```python
import imp
imp.find_module("_msprime")
```

**Comment by petrelharp** [comment]
I put this call in the failing test, so it tells me now:
```
======================================================================
FAIL: test_missing_columns (tests.test_dict_encoding.TestMissingData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/peter/projects/tskit-dev/msprime/tests/test_dict_encoding.py", line 198, in test_missing_columns
    lwt.fromdict(d)
AssertionError: ValueError not raised
-------------------- >> begin captured stdout << ---------------------
(<_io.BufferedReader name='/home/peter/projects/tskit-dev/msprime/_msprime.cpython-37m-x86_64-linux-gnu.so'>, '/home/peter/projects/tskit-dev/msprime/_msprime.cpython-37m-x86_64-linux-gnu.so', ('.cpython-37m-x86_64-linux-gnu.so', 'rb', 3))

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
msprime.ancestry: DEBUG: Setting initial model {'name': 'hudson'}
msprime.ancestry: DEBUG: Running simulation until maximum: inf
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
```

Removing and re-making the named file (`_msprime.cpython-37m-x86_64-linux-gnu.so`) indeed produces the same error.

**Comment by jeromekelleher** [comment]
This is very strange. There must be something weird in your python installation. How about trying it in a venv, with a fresh installation of the dev requirements?

ps. It's really not a good idea to use ``python3 setup.py install`` - it does weird things that aren't quite compatible with pip.

**Comment by jeromekelleher** [comment]
Any update on this @petrelharp?

**Comment by petrelharp** [comment]
No, sorry, I haven't gotten back to it yet. Will try for it today.

**Comment by petrelharp** [comment]
Yep - in a virtualenv everything is OK. I must have a wierd module somewhere; if I figure out what the problem was I'll report back, but will close this in the meantime.

**Comment by jeromekelleher** [comment]
I bet it's from ``setup.py install``ing. Probably best to clear out your installed msprime modules manually, as pip uninstall doesn't work when you have mixed installation methods.

**Comment by grahamgower** [comment]
If you've `pip install`'d the stable version and also run `setup.py develop`, then both versions can be removed by running `pip uninstall` twice in succession.

**Comment by petrelharp** [comment]
Hah - the problem was from having a development version of tskit, instead of 0.2.3. Sorry about the noise.
