### ISSUE TITLE
in verification.py:  test  MsMiscExamples fails

### ISSUE THREAD

**Issue by eldonb** [tskit-dev/msprime#1313]
I think I am running the msprime version as of  Nov 24, 2020  on  Debian:
it looks like there are 2 errors,  both receiving a float  when an integer  type was expected.
one error seems to be in  test_konrad_1,  the other one in the  seaborn package 

python3 verification.py --test-class MsMiscExamples
/usr/lib/python3/dist-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
  0%|                                                                                                                                                                  | 0/5 [00:00<?, ?it/s]2020-11-24 18:14:47,979 [30558] INFO     root: running 5 tests using 1 processes
2020-11-24 18:14:47,979 [30558] INFO     root: Running TestInstance(test_class='MsMiscExamples', method_name='test_konrad_1')
2020-11-24 18:14:52,082 [30558] CRITICAL root: Traceback (most recent call last):
  File "/home/bjarki/.local/lib/python3.7/site-packages/numpy/core/function_base.py", line 117, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "verification.py", line 4871, in <module>
    main()
  File "verification.py", line 4867, in main
    run_tests(suite, args)
  File "verification.py", line 4806, in run_tests
    runner.run(tests, args.output_dir, args.num_threads, not args.no_progress)
  File "verification.py", line 4774, in run
    self.__run_sequential(tests, basedir, progress)
  File "verification.py", line 4746, in __run_sequential
    test.run(basedir)
  File "verification.py", line 4707, in run
    method()
  File "verification.py", line 568, in test_konrad_1
    self._run(cmd)
  File "verification.py", line 366, in _run
    self._run_coalescent_stats(cmd)
  File "verification.py", line 354, in _run_coalescent_stats
    self._plot_stats("coalescent", df_msp, df_ms, "msp", "ms")
  File "verification.py", line 258, in _plot_stats
    plot_breakpoints_hist(flatten(v1), flatten(v2), df1_name, df2_name)
  File "verification.py", line 213, in plot_breakpoints_hist
    sns.kdeplot(v1, color="b", label=v1_name, shade=True, legend=False)
  File "/usr/lib/python3/dist-packages/seaborn/distributions.py", line 691, in kdeplot
    cumulative=cumulative, **kwargs)
  File "/usr/lib/python3/dist-packages/seaborn/distributions.py", line 283, in _univariate_kdeplot
    cumulative=cumulative)
  File "/usr/lib/python3/dist-packages/seaborn/distributions.py", line 355, in _statsmodels_univariate_kde
    kde.fit(kernel, bw, fft, gridsize=gridsize, cut=cut, clip=clip)
  File "/usr/lib/python3/dist-packages/statsmodels/nonparametric/kde.py", line 146, in fit
    clip=clip, cut=cut)
  File "/usr/lib/python3/dist-packages/statsmodels/nonparametric/kde.py", line 475, in kdensityfft
    grid,delta = np.linspace(a,b,gridsize,retstep=True)
  File "<__array_function__ internals>", line 6, in linspace
  File "/home/bjarki/.local/lib/python3.7/site-packages/numpy/core/function_base.py", line 121, in linspace
    .format(type(num)))
TypeError: object of type <class 'numpy.float64'> cannot be safely interpreted as an integer.

**Comment by jeromekelleher** [comment]
Great to see you're running this code @eldonb!

I think this must be an issue with your Python package installs. It looks like you have a mixture of installations from Debian packages and pypi, which can be a bit painful. I can see seaborn is living in /usr/lib, which probably means its installed from a Debian package. I would try ``apt remove python-seaborn``, and then ``python3 -m pip install -r requirements/development.txt --upgrade --user``. This should upgrade all of your user packages.

**Comment by eldonb** [comment]
thanks @jeromekelleher , this seems to have worked: 

I added   

seaborn  

to my  requirements/development.txt  file

however, python now complains about   logsumexp in  scipy.misc:

there are python modules trying to import   logsumexp from  scipy.misc,  which seems not to work, however 

from scipy.special import logsumexp

works, but  I am not sure how to tell python to  do that  


python3 verification.py --test-class MsmsSweeps
/usr/lib/python3/dist-packages/statsmodels/compat/pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
Traceback (most recent call last):
  File "verification.py", line 95, in <module>
    import statsmodels.api as sm  # noqa: E402
  File "/usr/lib/python3/dist-packages/statsmodels/api.py", line 16, in <module>
    from .tsa import api as tsa
  File "/usr/lib/python3/dist-packages/statsmodels/tsa/api.py", line 24, in <module>
    from .regime_switching.markov_regression import MarkovRegression
  File "/usr/lib/python3/dist-packages/statsmodels/tsa/regime_switching/markov_regression.py", line 13, in <module>
    from statsmodels.tsa.regime_switching import markov_switching
  File "/usr/lib/python3/dist-packages/statsmodels/tsa/regime_switching/markov_switching.py", line 15, in <module>
    from scipy.misc import logsumexp
ImportError: cannot import name 'logsumexp' from 'scipy.misc' (/usr/local/lib/python3.7/dist-packages/scipy/misc/__init__.py)

**Comment by jeromekelleher** [comment]
So you've got statsmodel installed from Debian now, which is an old version. It's a lot simpler to not use the Debian packages anything other than the base Python installation - that way you can keep things up to date. It's probably easiest to remove as many of the python3-[package] Debian packages using apt as you can.

**Comment by eldonb** [comment]
upgraded statsmodels using:
python3 -m pip install --upgrade git+https://github.com/statsmodels/statsmodels

and now something works,  but not  MsmsSweeps (does not find ./data/discoal): 

python3 verification.py --test-class MsmsSweeps
  0%|                                                                                                                                                                 | 0/11 [00:00<?, ?it/s]2020-11-26 17:36:05,005 [26151] INFO     root: running 11 tests using 1 processes
2020-11-26 17:36:05,005 [26151] INFO     root: Running TestInstance(test_class='MsmsSweeps', method_name='test_neutral_msms_vs_msp')
  9%|█████████████▉                                                                                                                                           | 1/11 [00:20<03:22, 20.29s/it]2020-11-26 17:36:25,300 [26151] INFO     root: Running TestInstance(test_class='MsmsSweeps', method_name='test_selective_discoal_vs_msp')
2020-11-26 17:36:25,300 [26151] WARNING  root: When compared with discoal, selected allele frequency options are recalculated following discoal's way
2020-11-26 17:36:25,316 [26151] CRITICAL root: Traceback (most recent call last):
  File "verification.py", line 4872, in <module>
    main()
  File "verification.py", line 4868, in main
    run_tests(suite, args)
  File "verification.py", line 4807, in run_tests
    runner.run(tests, args.output_dir, args.num_threads, not args.no_progress)
  File "verification.py", line 4775, in run
    self.__run_sequential(tests, basedir, progress)
  File "verification.py", line 4747, in __run_sequential
    test.run(basedir)
  File "verification.py", line 4708, in run
    method()
  File "verification.py", line 1106, in test_selective_discoal_vs_msp
    "100 300 -t 20 -r 20 50000"
  File "verification.py", line 1091, in _cmp_discoal_vs_msp_via_msms_cmd
    df_discoal = self._run_discoal_sample_stats(cmd)
  File "verification.py", line 1082, in _run_discoal_sample_stats
    return self._run_sample_stats(_discoal_executable + discoal_cmd.split(" "))
  File "verification.py", line 235, in _run_sample_stats
    p1 = subprocess.Popen(args, stdout=subprocess.PIPE)
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './data/discoal': './data/discoal'

**Comment by jeromekelleher** [comment]
OK, this one isn't obvious! You need to build the software that's in the ``data`` directory: ``cd data && make``.

**Comment by eldonb** [comment]
now it works,  although I had to  run the  discoal part in the Makefile  line by line,  I don't know why
I think can close this now,  thanks @jeromekelleher

**Comment by jeromekelleher** [comment]
Great!
