### ISSUE TITLE
possibly duplicated metadata keys when calling DemographyDebugger

### ISSUE THREAD

**Issue by grahamgower** [tskit-dev/msprime#1401]
Stdpopsim tests currently fail. E.g.
```
nosetests -x tests/
......................................................................................................................................................................E
======================================================================
ERROR: test_simulate_nonexistent_param (tests.test_engines.TestBehaviour)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/grg/src/stdpopsim/tests/test_engines.py", line 70, in test_simulate_nonexistent_param
    engine.simulate(**good_kwargs)
  File "/home/grg/src/stdpopsim/stdpopsim/slim_engine.py", line 1098, in simulate
    recap_epoch = slim_makescript(
  File "/home/grg/src/stdpopsim/stdpopsim/slim_engine.py", line 568, in slim_makescript
    dd = msprime.DemographyDebugger(
  File "/home/grg/.local/lib/python3.9/site-packages/msprime/demography.py", line 1047, in __init__
    self._make_epochs()
  File "/home/grg/.local/lib/python3.9/site-packages/msprime/demography.py", line 1060, in _make_epochs
    simulator = ancestry._parse_sim_ancestry(
  File "/home/grg/.local/lib/python3.9/site-packages/msprime/ancestry.py", line 962, in _parse_sim_ancestry
    demography.insert_populations(initial_state)
  File "/home/grg/.local/lib/python3.9/site-packages/msprime/demography.py", line 177, in insert_populations
    raise ValueError(
ValueError: Cannot set standard metadata key(s) ['description'] using extra_metadata. Please set using the corresponding property of the Population class.
```

In stdpopsim, we set the `"description"` key in the `metadata` attribute of each `msprime.PopulationConfiguration`. This is passed into msprime's `Population.from_old_style()`, which puts the pop_config metadata into the `Population.extra_metadata` field. Finally, when the extra metadata is resolved in `demography.insert_populations()`, this conflicts with the standard "description" metadata key.

**Comment by jeromekelleher** [comment]
Good catch. We should check the input metadata in ``from_old_style`` to see if it has any of the standard keys, and put them in from there to avoid this issue.

**Comment by jeromekelleher** [comment]
We can pop out another alpha to fix this - can you see if there's any other gotchas in stdpopsim please?
