### ISSUE TITLE
test_sweep_no_rec_ex2 flakey

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#1505]
I'm getting a good few errors in the Sweep stats tests @andrewkern, looking like this:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "verification.py", line 5446, in run
    method()
  File "verification.py", line 904, in test_sweep_no_rec_ex2
    self._run(cmd)
  File "verification.py", line 874, in _run
    for ts in replicates:
  File "/home/jk/work/github/msprime/msprime/ancestry.py", line 1372, in run_replicates
    self.run()
  File "/home/jk/work/github/msprime/msprime/ancestry.py", line 1324, in run
    self._run_until(model_start_time, event_chunk, debug_func)
  File "/home/jk/work/github/msprime/msprime/ancestry.py", line 1298, in _run_until
    while super().run(end_time, event_chunk) == _msprime.EXIT_MAX_EVENTS:
msprime._msprime.LibraryError: The simulation model supplied resulted in a parent node having a time value <= to its child. This can occur either as a result of multiple bottlenecks happening at the same time or because of numerical imprecision with very small population sizes.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "verification.py", line 5610, in <module>
    main()
  File "verification.py", line 5606, in main
    run_tests(suite, args)
  File "verification.py", line 5545, in run_tests
    runner.run(tests, args.output_dir, args.num_threads, not args.no_progress)
  File "verification.py", line 5515, in run
    self.__run_parallel(tests, basedir, num_threads, progress)
  File "verification.py", line 5507, in __run_parallel
    raise exception
msprime._msprime.LibraryError: The simulation model supplied resulted in a parent node having a time value <= to its child. This can occur either as a result of multiple bottlenecks happening at the same time or because of numerical imprecision with very small population sizes.
```

We need to make this more robust as it's making it difficult to run the actual suite.

There must be some issue where we're computing a zero time step in the allele frequency trajectory, I think.

Can you have a look at this please?

**Comment by andrewkern** [comment]
yup will do.

**Comment by andrewkern** [comment]
ugh, i can't get this to throw an error on our system....

**Comment by andrewkern** [comment]
okay I was able to reproduce the bug by increasing the sample size dramatically. this issue seems to be that when sample size is large, or selection very strong, we can get an event that occurs during the sweep at time zero. this isn't an issue with the trajectory, per se, but instead that the first coalescent even during the sweep is effectively at time zero.

One ugly hack would be to add a tiny amount of time to the front of the sweep phase of things. I'd be curious to hear @petrelharp's opinion on what I might do here.

**Comment by petrelharp** [comment]
If it's numerical issues, I'm not sure what you can do other than add an epsilon? This is done elsewhere in the code: https://github.com/tskit-dev/msprime/blob/9d0104ad63b963c793e063f807cee5964d3defb7/lib/msprime.c#L3821
