### ISSUE TITLE
node times for previously inactive populations are wrong

### ISSUE THREAD

**Issue by grahamgower** [tskit-dev/msprime#1658]
```python
# b.py
import msprime

demog = msprime.Demography()
# initialize populations
demog.add_population(name="ANC", initial_size=0, initially_active=False)
demog.add_population(name="A", initial_size=100, initially_active=True)
demog.add_population(name="B", initial_size=100, initially_active=True)
demog.add_population_split(time=20, ancestral="ANC", derived=["A", "B"])

demog.debug().print_history()
msprime.sim_ancestry(samples={"A": 10, "B": 10}, demography=demog)
```

```
 $ python -c "import msprime; print(msprime.__version__)"
1.0.0

$ python b.py
DemographyDebugger
╠═══════════════════════════════╗
║ Epoch[0]: [0, 20) generations ║
╠═══════════════════════════════╝
╟    Populations (total=3 active=2)
║    ┌───────────────────────────────────────────┐
║    │   │   start│     end│growth_rate  │ A │ B │
║    ├───────────────────────────────────────────┤
║    │  A│   100.0│   100.0│ 0           │ 0 │ 0 │
║    │  B│   100.0│   100.0│ 0           │ 0 │ 0 │
║    └───────────────────────────────────────────┘
╟    Events @ generation 20
║    ┌────────────────────────────────────────────────────────────────────────────┐
║    │  time│type        │parameters       │effect                                │
║    ├────────────────────────────────────────────────────────────────────────────┤
║    │    20│Population  │derived=[A, B],  │Moves all lineages from derived       │
║    │      │Split       │ancestral=ANC    │populations 'A' and 'B' to the        │
║    │      │            │                 │ancestral 'ANC' population. Also set  │
║    │      │            │                 │the derived populations to inactive,  │
║    │      │            │                 │and all migration rates to and from   │
║    │      │            │                 │the derived populations to zero.      │
║    └────────────────────────────────────────────────────────────────────────────┘
╠═════════════════════════════════╗
║ Epoch[1]: [20, inf) generations ║
╠═════════════════════════════════╝
╟    Populations (total=3 active=1)
║    ┌──────────────────────────────────┐
║    │     │  start│   end│growth_rate  │
║    ├──────────────────────────────────┤
║    │  ANC│    0.0│   0.0│ 0           │
║    └──────────────────────────────────┘
Traceback (most recent call last):
  File "/tmp/b.py", line 11, in <module>
    msprime.sim_ancestry(samples={"A": 10, "B": 10}, demography=demog)
  File "/home/grg/.local/lib/python3.9/site-packages/msprime/ancestry.py", line 1166, in sim_ancestry
    return _wrap_replicates(
  File "/home/grg/.local/lib/python3.9/site-packages/msprime/ancestry.py", line 673, in _wrap_replicates
    deque = collections.deque(iterator, maxlen=1)
  File "/home/grg/.local/lib/python3.9/site-packages/msprime/ancestry.py", line 1437, in run_replicates
    self.run()
  File "/home/grg/.local/lib/python3.9/site-packages/msprime/ancestry.py", line 1402, in run
    exit_reason = self._run_until(end_time, event_chunk, debug_func)
  File "/home/grg/.local/lib/python3.9/site-packages/msprime/ancestry.py", line 1367, in _run_until
    ret = ExitReason(super().run(end_time, event_chunk))
msprime._msprime.LibraryError: The simulation model supplied resulted in a parent node having a time value <= to its child. This can occur either as a result of multiple bottlenecks happening at the same time or because of numerical imprecision with very small population sizes.
```

**Comment by grahamgower** [comment]
Nevermind, I forgot to set a non-zero population size for `ANC`.
