### ISSUE TITLE
problems with gsl version in pyslim 1.0.3

### ISSUE THREAD

**Issue by ShyamieG** [tskit-dev/msprime#2187]
I recently updated to pyslim version 1.0.3 (via conda) following [Martin Petr's advice](https://twitter.com/fleventy5/status/1673379805117530287), and have since been getting this error:

```
Traceback (most recent call last):
  File "/hpc/group/goldberg/ssg36/scripts/P_vivax/ts_processing_scripts/2_recapitate_ts.py", line 18, in <module>
    import pyslim
  File "/hpc/group/goldberg/ssg36/miniconda3/envs/slim-env/lib/python3.9/site-packages/pyslim/__init__.py", line 4, in <module>
    from pyslim.slim_metadata import *       # NOQA
  File "/hpc/group/goldberg/ssg36/miniconda3/envs/slim-env/lib/python3.9/site-packages/pyslim/slim_metadata.py", line 6, in <module>
    from .provenance import *
  File "/hpc/group/goldberg/ssg36/miniconda3/envs/slim-env/lib/python3.9/site-packages/pyslim/provenance.py", line 6, in <module>
    import msprime
  File "/hpc/group/goldberg/ssg36/miniconda3/envs/slim-env/lib/python3.9/site-packages/msprime/__init__.py", line 28, in <module>
    from msprime._msprime import (
ImportError: libgsl.so.25: cannot open shared object file: No such file or directory
```

It seems as though it is looking for an earlier version of gsl, but installs version 2.7.1? I was able to manually downgrade to gsl version 2.6, but then my script stopped with another import error looking for libopenblas:

```
Traceback (most recent call last):
  File "/hpc/group/goldberg/ssg36/scripts/P_vivax/ts_processing_scripts/2_recapitate_ts.py", line 18, in <module>
    import pyslim
  File "/hpc/group/goldberg/ssg36/miniconda3/envs/slim-env/lib/python3.9/site-packages/pyslim/__init__.py", line 4, in <module>
    from pyslim.slim_metadata import *       # NOQA
  File "/hpc/group/goldberg/ssg36/miniconda3/envs/slim-env/lib/python3.9/site-packages/pyslim/slim_metadata.py", line 6, in <module>
    from .provenance import *
  File "/hpc/group/goldberg/ssg36/miniconda3/envs/slim-env/lib/python3.9/site-packages/pyslim/provenance.py", line 6, in <module>
    import msprime
  File "/hpc/group/goldberg/ssg36/miniconda3/envs/slim-env/lib/python3.9/site-packages/msprime/__init__.py", line 28, in <module>
    from msprime._msprime import (
ImportError: libopenblas.so.0: cannot open shared object file: No such file or directory
```

I'm trying to install the right version of libopenblas now, but wondering if there is an easier way to resolve this?

**Comment by jeromekelleher** [comment]
I'm afraid this is almost certainly something to do with conda @ShyamieG. The only thing I can suggestion to start again with a new environment :cry:

**Comment by jeromekelleher** [comment]
I'm going to close the issue because it's likely nothing to do with msprime itself, but please do let us know how you get on and whether reinstalling in a fresh environment solves things.

**Comment by ShyamieG** [comment]
Hmm, ok. A fresh environment is the first thing I tried and it did not help.

**Comment by molpopgen** [comment]
Install msprime into your conda env using pip instead of conda.  (If you use YAML files to manage envs, mark it as a pip dependency there.)  msprime has "wheels" for most platforms.  Those wheels vendor in their own GSL.

**Comment by ShyamieG** [comment]
thanks @molpopgen ! that worked
