### ISSUE TITLE
Infinite waiting time in DTWF random test.

### ISSUE THREAD

**Issue by jeromekelleher** [tskit-dev/msprime#628]
Running ``dtwf_vs_coalescent_random_1`` I get
```
dtwf_vs_coalescent_random_1
Running:  {'migration_matrix': [[0.0, 0.15641008119227764], [0.3933221408503581, 0.0]], 'population_configurations': [<msprime.simulations.PopulationConfiguration object at 0x7ff479f71d68>, <msprime.simulations.PopulationConfiguration object at 0x7ff479f71e48>], 'demographic_events': [{'type': 'population_parameters_change', 'time': 648, 'growth_rate': 0.009679846244129, 'initial_size': 666, 'population': 0}, {'type': 'population_parameters_change', 'time': 1071, 'growth_rate': 0.006809640451234402, 'initial_size': 529, 'population': 1}, {'type': 'migration_rate_change', 'time': 1071, 'rate': 0.41186677247615133, 'matrix_index': (1, 0)}, {'type': 'population_parameters_change', 'time': 1582, 'growth_rate': -0.0007316775619632182, 'initial_size': 558, 'population': 1}, {'type': 'mass_migration', 'time': 2000, 'source': 1, 'dest': 0, 'proportion': 1.0}, {'type': 'population_parameters_change', 'time': 2000, 'growth_rate': 0.01, 'initial_size': 1000, 'population': 0}], 'num_replicates': 200, 'recombination_map': <msprime.simulations.RecombinationMap object at 0x7ff479f71cc0>, 'model': 'hudson'}
Running:  {'migration_matrix': [[0.0, 0.15641008119227764], [0.3933221408503581, 0.0]], 'population_configurations': [<msprime.simulations.PopulationConfiguration object at 0x7ff479f71d68>, <msprime.simulations.PopulationConfiguration object at 0x7ff479f71e48>], 'demographic_events': [{'type': 'population_parameters_change', 'time': 648, 'growth_rate': 0.009679846244129, 'initial_size': 666, 'population': 0}, {'type': 'population_parameters_change', 'time': 1071, 'growth_rate': 0.006809640451234402, 'initial_size': 529, 'population': 1}, {'type': 'migration_rate_change', 'time': 1071, 'rate': 0.41186677247615133, 'matrix_index': (1, 0)}, {'type': 'population_parameters_change', 'time': 1582, 'growth_rate': -0.0007316775619632182, 'initial_size': 558, 'population': 1}, {'type': 'mass_migration', 'time': 2000, 'source': 1, 'dest': 0, 'proportion': 1.0}, {'type': 'population_parameters_change', 'time': 2000, 'growth_rate': 0.01, 'initial_size': 1000, 'population': 0}], 'num_replicates': 200, 'recombination_map': <msprime.simulations.RecombinationMap object at 0x7ff479f71cc0>, 'model': 'dtwf'}
Traceback (most recent call last):
  File "verification.py", line 2105, in <module>
    main()
  File "verification.py", line 2101, in main
    verifier.run(keys)
  File "verification.py", line 257, in run
    runner()
  File "verification.py", line 1302, in f
    recombination_map=recombination_map)
  File "verification.py", line 1062, in run_dtwf_coalescent_comparison
    for ts in replicates:
  File "/home/jk/work/github/msprime/msprime/simulations.py", line 118, in _replicate_generator
    sim.run(max_time)
  File "/home/jk/work/github/msprime/msprime/simulations.py", line 671, in run
    self.ll_sim.run(max_time)
_msprime.LibraryError: Infinite waiting time until next simulation event.
```

**Comment by DomNelson** [comment]
This I believe can only happen [here](https://github.com/tskit-dev/msprime/blob/75a11d00275aaa2ebec0f7c357c2024f160f0bce/lib/msprime.c#L2521) in the DTWF:

```
// This may not be ideal, but with low migration / high growth rates it
// is possible for populations to reach zero individuals before all
// lineages coalesce. We round up to avoid this.
N = (uint32_t) ceil(
    msp_get_population_size(self, pop) * self->model.population_size);
if (N == 0) {
    ret = MSP_ERR_INFINITE_WAITING_TIME;
    goto out;
}
```

and in these random checks it's possible that we're underflowing on pop size before all lineages coalesce. Is it worth considering a minimum of 1 individual for each pop that still has extant lineages? Or do you think something other than underflow could be going on?

**Comment by jeromekelleher** [comment]
Well, it may be that this is is the right behaviour for the code, and we just need to constrain the random tests to avoid it happening. The tests must be reliable and run reasonably quickly, as they are part of the release process.

**Comment by DomNelson** [comment]
It's true if this happens it's essentially a degenerate demographic model, especially in the DTWF case where we need an integer population size. I'll open a PR with more restricted random tests.

Speaking of test running quickly, I did add quite a few for the DTWF model and several are quite slow. I could look at cutting those down if you feel it's overkill.

**Comment by jeromekelleher** [comment]
> Speaking of test running quickly, I did add quite a few for the DTWF model and several are quite slow. I could look at cutting those down if you feel it's overkill.

It'd be nice to run all the tests in ~30 minutes as a quick pre-release test to make sure nothing has badly blown up. Maybe we could add a command line option to the script for ``--extended-tests`` or something?

**Comment by DomNelson** [comment]
That sounds like a good compromise. The comprehensive tests were great for ironing out issues in the DTWF but are probably overkill for anything except pretty low-level changes. I'll do a bit of profiling and see about pulling out a streamlined core of tests.

**Comment by jeromekelleher** [comment]
Is this resolved @DomNelson?

**Comment by jeromekelleher** [comment]
Bump - did we decide to close this one @DomNelson or do we need to pull out some tests?

**Comment by jeromekelleher** [comment]
Bumping again - @DomNelson, what's the status here?
