### ISSUE TITLE
setuptools-scm error

### ISSUE THREAD

**Issue by ebioman** [tskit-dev/msprime#753]
Hello
I am running into issues with the setuptools-scm if building the package manually:

```bash
+ /software/bin/python3 setup.py build
Traceback (most recent call last):
  File "setup.py", line 175, in <module>
    cmdclass={"build_ext": local_build_ext},
  File "/software/lib/python3.5/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/software/lib64/python3.5/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/software/lib/python3.5/site-packages/setuptools/dist.py", line 447, in __init__
    k: v for k, v in attrs.items()
  File "/software/lib64/python3.5/distutils/dist.py", line 281, in __init__
    self.finalize_options()
  File "/software/lib/python3.5/site-packages/setuptools/dist.py", line 739, in finalize_options
    ep.load()(self, ep.name, value)
  File "/software/lib/python3.5/site-packages/setuptools_scm/integration.py", line 23, in version_keyword
    dist.metadata.version = get_version(**value)
  File "/software/lib/python3.5/site-packages/setuptools_scm/__init__.py", line 144, in get_version
    parsed_version = _do_parse(config)
  File "/software/lib/python3.5/site-packages/setuptools_scm/__init__.py", line 111, in _do_parse
    "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
LookupError: setuptools-scm was unable to detect version for '/builddir/build/BUILD/python3-Vcluster-python-msprime-0.7.0-1.el7'.
```
Any idea how to fix this ?

**Comment by jeromekelleher** [comment]
Can you give a bit more information on how you're building this please?

Also, is there any particular reason for building from git rather than using the distributed packages? The git version is really only intended for developers and should not be used for production simulations.

**Comment by ebioman** [comment]
Thx for the quick reply. 
I am building it on CentOS7 via rpmbuild in a sandbox to fabricate at the end RPMs for our cluster in a research environment.
The problem is that we cant use pip neither conda and have to build packages in a completely isolated sanbox. I tried using both, the PyPi tarball and the release tarball from this Git (both version 0.7.0).

**Comment by jeromekelleher** [comment]
Thanks @ebioman, this is very helpful info. Can you paste in the error that you get when you run from the tarball downloaded from PyPI please?

Can you use ``pip`` when you're running rpmbuild, or does it need ``python setup.py`` (using ``bdist rpm`` maybe?). Sorry, I'm not very well versed on rpms, but I'm happy to help get this working and I'm sure there's a solution.

**Comment by jeromekelleher** [comment]
Just wondering, is ``git`` installed in your sandbox? If you're using pip, git shouldn't be necessary, but if you run ``setup.py`` then probably setuptools_scm will try to figure out what the current version is using git. Maybe this is the issue?

**Comment by ebioman** [comment]
Had a chat with a co-worker who ran into similar problems with different softs.
The issue seems to be that setuptools_scm generates often this problem and there are essentially 2 solutions:

 - get the entire git and package it as a tarball manually, which then includes the needed meta-data
 - hack manually the setup.py

I am currently doing the latter by setting: `sed -i 's@use_scm_version={"write_to": "msprime/_version.py"}@version="0.7.0"@' setup.py`

Obviously an ugly hack, but currently proceeds - fingers crossed

**Comment by jeromekelleher** [comment]
It's a bit weird, because the PyPI distributed tarball **does** contain the metadata (the ``msprime/_version.py`` file); you don't need to have git installed when using ``pip install <tarball_file>``. I'm surprised that wget'ing the tarball from PyPI doesn't work.

Your sed-hack should work fine though; let me know how it works out so we can close this issue if it's resolved.

**Comment by jeromekelleher** [comment]
Closing due to inactivity; feel free to reopen if this is still a live issue.

**Comment by ebioman** [comment]
Sorry forgot to close it.
I pulled again from PyPi and did not run into that issue anymore.
Thanks

Jerome Kelleher <notifications@github.com> schrieb am Mo., 13. Mai 2019,
12:35:
