### ISSUE TITLE
msprime not linking to gsl/cblas

### ISSUE THREAD

**Issue by schimar** [tskit-dev/msprime#788]
Hey there, 

when installing msprime (both with python 2.7 and 3.7), I am unable to load the module (in python nor with msp/mspms), where I get the following errors, 

with **python2.7**:
```
Traceback (most recent call last):
  File "/home/schimar/.local/bin/mspms", line 6, in <module>
    from msprime.cli import mspms_main
  File "/home/schimar/.local/lib/python2.7/site-packages/msprime/__init__.py", line 52, in <module>
    from msprime.provenance import __version__
  File "/home/schimar/.local/lib/python2.7/site-packages/msprime/provenance.py", line 28, in <module>
    import _msprime
ImportError: /usr/local/lib/libgsl.so.23: undefined symbol: cblas_ctrmv
```
and with **python3.7**:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/schimar/.local/lib/python3.7/site-packages/msprime/__init__.py", line 49, in <module>
    from msprime.provenance import __version__
  File "/home/schimar/.local/lib/python3.7/site-packages/msprime/provenance.py", line 25, in <module>
    import _msprime
ImportError: /usr/local/lib/libgsl.so.23: undefined symbol: cblas_ctrmv
```

Apparently, libgsl is found, yet not linked to libcblas. 
I am running ubuntu 19.04, with the built-in python distro (i.e. installed using pip) 

Thanks for any help, 
all the best, 
m

**Comment by jeromekelleher** [comment]
Thanks @schimar - can you give some details about your linux distro please?

**Comment by schimar** [comment]
> Thanks @schimar - can you give some details about your linux distro please?
Sorry, forgot to include this in the first post. I've updated it now. let me know if you want more detail.

**Comment by jeromekelleher** [comment]
How did you install GSL @schimar? (I ask because I see GSL is installed in /usr/local wheras it used to be in /usr for Debian/Ubuntu --- maybe this has changed recently?)

**Comment by schimar** [comment]
hm, no special install, simply with 
```
apt install libgsl-dev
```

**Comment by jeromekelleher** [comment]
I can only imagine this is some version of [this problem](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=907119). 

Would you mind trying something out please @schimar? If you clone a local copy of msprime (see the [dev docs](https://msprime.readthedocs.io/en/latest/development.html) for help here) and reverse the order of 'gsl' and 'gsl_cblas' on [this line](https://github.com/tskit-dev/msprime/blob/master/setup.py#L99), does it fix the problem?

**Comment by schimar** [comment]
ok, tried it with the following:
```
git clone https://github.com/schimar/msprime.git --recurse-submodules
# changed the order of the two libs in setup.py to ["gslcblas", "gsl"], as suggested & then:
python3 -m pip install -r requirements/development.txt
make 
python3 -m nose -vs
```
with the following result:
```
Failure: ImportError (/usr/local/lib/libgsl.so.23: undefined symbol: cblas_ctrmv) ... ERROR
Failure: ImportError (/usr/local/lib/libgsl.so.23: undefined symbol: cblas_ctrmv) ... ERROR

======================================================================
ERROR: Failure: ImportError (/usr/local/lib/libgsl.so.23: undefined symbol: cblas_ctrmv)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.7/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.7/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/schimar/bio/msprime/msprime/__init__.py", line 49, in <module>
    from msprime.provenance import __version__
  File "/home/schimar/bio/msprime/msprime/provenance.py", line 25, in <module>
    import _msprime
ImportError: /usr/local/lib/libgsl.so.23: undefined symbol: cblas_ctrmv

======================================================================
ERROR: Failure: ImportError (/usr/local/lib/libgsl.so.23: undefined symbol: cblas_ctrmv)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/usr/lib/python3/dist-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python3/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/usr/lib/python3.7/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.7/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/schimar/bio/msprime/tests/__init__.py", line 25, in <module>
    import msprime
  File "/home/schimar/bio/msprime/msprime/__init__.py", line 49, in <module>
    from msprime.provenance import __version__
  File "/home/schimar/bio/msprime/msprime/provenance.py", line 25, in <module>
    import _msprime
ImportError: /usr/local/lib/libgsl.so.23: undefined symbol: cblas_ctrmv

----------------------------------------------------------------------
Ran 2 tests in 0.263s

FAILED (errors=2)
```

**Comment by jeromekelleher** [comment]
Thanks @schimar, this is very helpful! Can you paste in the output of  ``gsl-config --libs`` please?

**Comment by schimar** [comment]
yes of course, here you go:
```
-L/usr/lib/x86_64-linux-gnu -lgsl -lgslcblas -lm
```

**Comment by jeromekelleher** [comment]
Hmmm. Not sure I can help much here then @schimar - it must be an upstream bug of some sort with Ubuntu's GSL packaging.

The best workaround is to use conda, I'm afraid.

**Comment by schimar** [comment]
I was afraid you might say that.  it does work on my laptop though, and I'll get it onto one of our HPCs here, so no need to "besmirch" my system with an extra python distro :) 

thanks so much for taking the time to look into this! 
best, 
martin

**Comment by petrelharp** [comment]
Did you try purging then reinstalling `libgsl-dev`?

**Comment by schimar** [comment]
Hey @petrelharp, 
thanks for the suggestion; but no, that didn't do it, unfortunately. 
best, 
m

**Comment by jeromekelleher** [comment]
Just as a data point here, this problem doesn't exist on Ubuntu 18.04:
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

Msprime installed and ran  here with the ``libgsl-dev`` package.

**Comment by jeromekelleher** [comment]
Closing this due to inactivity.
