### ISSUE TITLE
singularity container can conflict w/ home

### ISSUE THREAD

**Issue by agladstein** [tskit-dev/msprime#809]
I've discovered that your home environment can conflict with the msprime singularity container. I believe this happened to me when I tried to build a package locally with `setup.py` (probably `pylibseq` was the culprit), and I couldn't figure out how to clean up my home environment enough to have it not conflict.

I pulled the Docker image as a Singularity container
```
$ singularity pull docker://tskit/msprime:release-0.7.3
```

I then started an interactive container
```
$ singularity shell msprime-release-0.7.3.simg
Singularity: Invoking an interactive shell within container...

Singularity msprime-release-0.7.3.simg:~>
```

Finally, started python and imported `msprime`.
```
Singularity msprime-release-0.7.3.simg:~> python3
Python 3.6.8 (default, Jan 14 2019, 11:02:34)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import msprime
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/msprime/__init__.py", line 49, in <module>
    from msprime.provenance import __version__
  File "/usr/local/lib/python3.6/dist-packages/msprime/provenance.py", line 25, in <module>
    import _msprime
ImportError: /usr/lib/x86_64-linux-gnu/libgsl.so.23: undefined symbol: cblas_ctrmv
```

There are two workarounds:
1.  Ignore your home with the conflicting environment
```
$ singularity shell --contain msprime-release-0.7.3.simg
Singularity: Invoking an interactive shell within container...

Singularity msprime-release-0.7.3.simg:~> python3
Python 3.6.8 (default, Jan 14 2019, 11:02:34)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import msprime
>>>
```
or use a different path as your home that does not have a conflicting environment
```
$ singularity shell -H /new/path/to/home -e msprime-release-0.7.3.simg
Singularity: Invoking an interactive shell within container...

Singularity msprime-release-0.7.3.simg:~/cnn_classify_demography> python3
Python 3.6.8 (default, Jan 14 2019, 11:02:34)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import msprime
>>>
```
2. In python get rid of your local path
```
$ singularity shell msprime-release-0.7.3.simg
Singularity: Invoking an interactive shell within container...

Singularity msprime-release-0.7.3.simg:~> python3
Python 3.6.8 (default, Jan 14 2019, 11:02:34)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> for _path in sys.path:
...     if ".local" in _path:
...             sys.path.remove(_path)
...
>>> import msprime
>>>
```

There is probably a way to create the Docker image so the singularity container won't see the home environment, but I'm not sure how to do it. The Jupyter Notebook base docker images (https://hub.docker.com/r/jupyter/datascience-notebook) seem to have accomplished it.

I could add this workaround to the containerization docs in case anyone else runs into this problem.

**Comment by jeromekelleher** [comment]
Thanks for bringing this up @agladstein --- I guess the thing to do is add the workaround to the docs? I don't know enough about singularity to suggest anything else I'm afraid.
